language: node_js
node_js:
    - "0.8"

before_install:
    - sudo mkdir -p /srv/tomcat/tomcat1/webapps/
    - sudo chmod 777 /srv/tomcat/tomcat1/webapps
    - sudo apt-get update -qq
    - sudo apt-get install -qq libgeos-dev python-gdal

before_script:
    - python bootstrap.py --version 1.5.2 --distribute --download-base http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/ --setup-source http://pypi.camptocamp.net/distribute-0.6.22_fix-issue-227/distribute_setup.py

script:
    - buildout/bin/buildout -c buildout_prod.cfg
    - buildout/bin/nosetests chsdi/tests/functional/test_encoders.py
    - buildout/bin/nosetests chsdi/tests/functional/test_mortonspacekey.py
    - buildout/bin/nosetests chsdi/tests/functional/test_renderer.py

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/0cf68a26e25cc259e947
            on_success: change  # options: [always|never|change] default: always
            on_failure: always  # options: [always|never|change] default: always
            on_start: false     # default: false
