language: node_js
node_js:
    - "0.8"

before_script:
    - sudo pip install virtualenv
    - sudo groupadd geodata
    - make all

notifications:
    email:
        recipients:
            - re3-dev@googlegroups.com

